# Generated by Django 4.0.3 on 2022-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderID', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'Updates',
            },
        ),
        migrations.AlterField(
            model_name='driver',
            name='License',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='certificate',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
