# Generated by Django 4.0.3 on 2022-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_updates_alter_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='certificate',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
