# Generated by Django 4.0.3 on 2022-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_driver_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='BusLine',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='updates',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
