# Generated by Django 4.0.3 on 2022-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_updates_busline_alter_updates_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
    ]
