# Generated by Django 4.0.3 on 2022-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_schedule_trip_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='EndTime',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='StartTime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='BusLine',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='From',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='To',
            field=models.CharField(default='', max_length=100),
        ),
    ]
